### ISSUE TITLE
Backtrace when not using the stepping emulator

### ISSUE THREAD

**Issue by mads256h** [DEIS-Tools/DistributedExercisesAAU#46]
Using the command
```bash
python exercise_runner.py --lecture 0 --algorithm PingPong --type async --devices 3
```
python is 3.10 on my system

Gives the following backtrace:
```
Traceback (most recent call last):
  File "/home/mads/GitHub/DistributedExercisesAAU/exercise_runner.py", line 100, in <module>
    run_exercise(args.lecture[0], args.algorithm[0], args.type[0], args.devices[0], False)
  File "/home/mads/GitHub/DistributedExercisesAAU/exercise_runner.py", line 79, in run_exercise
    instance.shell.start()
    ^^^^^^^^^^^^^^
AttributeError: 'AsyncEmulator' object has no attribute 'shell'
```

It seems to run anyway, though.

**Comment by michelealbano** [comment]
We have just corrected it. We are patching the bug shortly.
